spring.application.name=chordax_mailing

server.port=8082

## mailing system from https://www.geeksforgeeks.org/spring-boot-sending-email-via-smtp/
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=piotrandrzejbar@gmail.com
##spring.mail.username=[google (gmail) account user name]
#spring.mail.password="eonz oeke sdhf oeui"
##spring.mail.password=[google (gmail) app password]
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
##spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=98e807f595b70b
spring.mail.password=a1ca3351bc4a7d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

########################### EUREKA ############################################
eureka.client.serviceUrl.defaultZone=http://localhost:8765/eureka
eureka.instance.preferIpAddress=true

