spring:
  application.name: chordax_mailing

########################### CONFIG ############################################
  config.import: optional:configserver:http://localhost:8888
  cloud.config.uri: http://localhost:8888

########################### H2 ############################################
#----------- to set mailing -----------------
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 98e807f595b70b
    password: a1ca3351bc4a7d
    properties.mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

################# EUREKA - SERVICE DISCOVERY ##########################
eureka:
  client.serviceUrl.defaultZone:
  instance.preferIpAddress:

########################### PORT ############################################
server.port: